site_name: SGRODOL
site_url: https://seeenorf.github.io/SGRODOL/

theme:
  name: material
  palette:
    - scheme: default
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode
    - scheme: slate
      toggle:
        icon: material/brightness-4
        name: Switch to light mode
  features:
    - navigation.instant
    - navigation.instant.progress
    - navigation.instant.preview
    - navigation.tracking
    - navigation.tabs
    - navigation.tabs.sticky
    - navigation.sections
    - navigation.expand
    - toc.integrate
    - navigation.top
    - search.suggest
    - search.highlight
    - search.share
    - content.code.copy

plugins:
  - search
  - tags:
      tags_file: tags.md
  - blog

markdown_extensions:
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences

extra_css:
  - assets/css/extra.css  # Aggiungi il CSS personalizzato per il logo

nav:
  - Home: index.md
  - Info:
      - Informazioni: about/Info.md
      - Canali: about/Progetti.md
      - Infanzia: about/Infanzia.md
  - Blog:
      - blog/index.md
  - Tags: tags.md
  - Codici importanti:
      - Codici utili per il sito: Codici/Codici Per Il Sito.md



