site_name: Project MNG
site_url: https://seeenorf.github.io/MNG/

theme:
  name: material
  logo: assets/SGRODOLLOGO.png
  palette:
    - scheme: default
      primary: purple
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode
    - scheme: slate
      primary: purple
      toggle:
        icon: material/brightness-4
        name: Switch to light mode
  features:
    - navigation.instant
    - navigation.instant.progress
    - navigation.instant.preview
    - navigation.tracking
    - navigation.tabs
    - navigation.tabs.sticky
    - navigation.sections
    - navigation.expand
    #- toc.integrate
    - navigation.top
    - search.suggest
    - search.highlight
    - search.share
    - content.code.copy

plugins:
  - search
  - tags:
      tags_file: tags.md
  - blog

markdown_extensions:
  - attr_list
  - md_in_html
  - pymdownx.blocks.caption
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences


nav:
  - Home: index.md
  - Info:
      - Informazioni: about/Info.md
      - Canali: about/Progetti.md
      - NON SEI MAI TU: about/NON-SEI-MAI-TU.md
  - Blog:
      - blog/index.md
  - Tags: tags.md
